# Generated by Django 5.2.8 on 2025-11-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('habitat', models.CharField(blank=True, max_length=150, null=True)),
                ('average_weight_kg', models.FloatField(blank=True, null=True)),
                ('lifespan_years', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
